import { useSelector } from 'react-redux';
import { RootState } from './store';

export const translations = {
  en: {
    'Bạn chưa đăng nhập': 'You are not logged in',
    'Hãy đăng nhập để sử dụng các chức năng cá nhân hóa!': 'Please log in to use personalized functions!',
    'Đăng nhập': 'Login',
    'hoặc': 'or',
    'Tạo tài khoản': 'Create account',
    'Đăng xuất': 'Logout',
    'Bạn có chắc chắn muốn đăng xuất?': 'Are you sure you want to logout?',
    'Hủy': 'Cancel',
    'Thông tin cá nhân': 'Personal Information',
    'Tên đăng nhập:': 'Username:',
    'Email:': 'Email:',
    'Số điện thoại:': 'Phone:',
    'Ngày sinh:': 'Date of birth:',
    'Giới tính:': 'Gender:',
    'Nam': 'Male',
    'Nữ': 'Female',
    'Chức năng': 'Functions',
    'Phim yêu thích': 'Favorite Movies',
    'Cinema': 'Cinema',
    'Khuyến mãi': 'Promotions',
    'Cài đặt': 'Settings',
    'Quản lý hệ thống': 'System Management',
    'Quản lý đặt vé': 'Booking Management',
    'Đổi mật khẩu': 'Change Password',
    'Chế độ tối': 'Dark Mode',
    'Ngôn ngữ (English/Tiếng Việt)': 'Language (English/Vietnamese)',
    'Đóng': 'Close',
    "Quản trị viên": "Administrator",
    "Nhân viên": "Staff",
    "Khách hàng": "Customer",
    "Email không được để trống": "Email is required",
    "Email không hợp lệ": "Invalid email",
    "OTP không được để trống": "OTP is required",
    "OTP phải có 6 chữ số": "OTP must be 6 digits",
    "Họ tên không được để trống": "Full name is required",
    "Số điện thoại không được để trống": "Phone number is required",
    "Số điện thoại không hợp lệ (10-11 chữ số)": "Invalid phone number (10-11 digits)",
    "Tên đăng nhập không được để trống": "Username is required",
    "Tên đăng nhập phải có ít nhất 3 ký tự": "Username must be at least 3 characters",
    "Mật khẩu không được để trống": "Password is required",
    "Mật khẩu phải có ít nhất 6 ký tự": "Password must be at least 6 characters",
    "Xác nhận mật khẩu không được để trống": "Confirm password is required",
    "Mật khẩu xác nhận không khớp": "Passwords do not match",
    "Ngày sinh không được để trống": "Date of birth is required",
    "Định dạng ngày sinh phải là YYYY-MM-DD": "Date of birth must be in YYYY-MM-DD format",
    "Năm sinh phải từ 1900 đến 2010": "Year of birth must be between 1900 and 2010",
    "Tháng phải từ 01 đến 12": "Month must be between 01 and 12",
    "Ngày phải từ 01 đến {daysInMonth} cho tháng {month}": "Day must be between 01 and {daysInMonth} for month {month}",
    "Thành công": "Success",
    "OTP đã được gửi đến email của bạn": "OTP has been sent to your email",
    "Lỗi": "Error",
    "Không thể gửi OTP": "Could not send OTP",
    "OTP hợp lệ! Vui lòng nhập thông tin tài khoản": "Valid OTP! Please enter your account information",
    "OTP không hợp lệ": "Invalid OTP",
    "OTP mới đã được gửi": "New OTP has been sent",
    "Nhập email của bạn": "Enter your email",
    "Nhập 6 chữ số OTP": "Enter 6-digit OTP",
    "Nhập họ và tên": "Enter full name",
    "Nhập số điện thoại": "Enter phone number",
    "Nhập tên đăng nhập": "Enter username",
    "Nhập mật khẩu": "Enter password",
    "Nhập lại mật khẩu": "Re-enter password",
    "Đăng ký tài khoản thành công!": "Account registered successfully!",
    "Đăng ký thất bại": "Registration failed",
    "OTP mới đã được gửi": "New OTP has been sent",
    "Quay lại": "Back",
    "Đăng ký": "Register",
    "Email": "Email",
    "Nhập email của bạn": "Enter your email",
    "Gửi OTP": "Send OTP",
    "Mã OTP": "OTP Code",
    "Nhập 6 chữ số OTP": "Enter 6-digit OTP",
    "OTP hết hạn sau:": "OTP expires in:",
    "Xác thực OTP": "Verify OTP",
    "Gửi lại OTP": "Resend OTP",
    "Họ và tên": "Full name",
    "Nhập họ và tên": "Enter your full name",
    "Số điện thoại": "Phone number",
    "Nhập số điện thoại": "Enter your phone number",
    "Tên đăng nhập": "Username",
    "Nhập tên đăng nhập": "Enter your username",
    "Mật khẩu": "Password",
    "Nhập mật khẩu": "Enter your password",
    "Xác nhận mật khẩu": "Confirm password",
    "Nhập lại mật khẩu": "Confirm your password",
    "Ngày sinh": "Date of birth",
    "YYYY-MM-DD (ví dụ: 1990-01-15)": "YYYY-MM-DD (e.g. 1990-01-15)",
    "Định dạng: YYYY-MM-DD (ví dụ: 1990-01-15)": "Format: YYYY-MM-DD (e.g. 1990-01-15)",
    "Đăng ký tài khoản mới": "Register a new account",
    "Đã có tài khoản?": "Already have an account?",
    "Đang xử lý...": "Processing...",
    'Không thể tải thông tin phim': 'Could not load movie information',
    'Không thể tải danh sách rạp': 'Could not load the list of cinemas',
    'Không thể tải suất chiếu': 'Could not load showtimes',
    'Chọn rạp': 'Select Cinema',
    'Chọn ngày': 'Select Date',
    'Suất chiếu': 'Showtimes',
    'Không có suất chiếu cho ngày này.': 'No showtimes for this date.',
    'Đang tải...': 'Loading...',
    'Lỗi tải dữ liệu': 'Error loading data',
    'Thử lại': 'Retry',
    'Chọn suất chiếu': 'Select Showtime',
    'Ngày': 'Date',
    'Rạp': 'Cinema',
    'Vui lòng nhập mã giảm giá': 'Please enter a discount code',
    'Mã giảm giá không hợp lệ hoặc đã hết hạn': 'Invalid or expired discount code',
    'Đơn hàng tối thiểu {minAmount} VNĐ để áp dụng mã này': 'A minimum order of {minAmount} VND is required to apply this code',
    'Đã áp dụng mã giảm giá: {name}': 'Applied discount code: {name}',
    'Không thể kiểm tra mã giảm giá. Vui lòng thử lại.': 'Could not verify discount code. Please try again.',
    'Vui lòng chọn ghế': 'Please select your seats',
    'Không tìm thấy thông tin suất chiếu': 'Showtime information not found',
    'Thông báo': 'Notification',
    'Vui lòng đăng nhập để đặt vé': 'Please log in to book tickets',
    'Đặt vé thành công!': 'Booking successful!',
    'Đặt vé thất bại': 'Booking failed',
    'Đặt vé': 'Book ticket',
    'Phim': 'Movies',
    'Rạp chiếu': 'Cinema',
    'Phòng chiếu': 'Hall',
    'Ghế đã chọn': 'Selected Seats',
    'ghế đã chọn': 'seats selected',
    'Chưa chọn ghế': 'No seats selected',
    'Mã giảm giá (tùy chọn)': 'Discount Code (optional)',
    'Nhập mã giảm giá': 'Enter discount code',
    'Áp dụng': 'Apply',
    'Xóa mã': 'Remove code',
    'Tóm tắt đơn hàng': 'Order Summary',
    'Số ghế đã chọn:': 'Number of seats selected:',
    'Số lượng ghế:': 'Number of seats:',
    'ghế': 'seats',
    'Giá mỗi vé:': 'Price per ticket:',
    'Giảm giá:': 'Discount:',
    'Tổng cộng:': 'Total:',
    'Mật khẩu cũ không được để trống': 'Old password is required',
    'Mật khẩu mới không được để trống': 'New password is required',
    'Mật khẩu mới phải có ít nhất 6 ký tự': 'New password must be at least 6 characters',
    'Mật khẩu mới phải khác mật khẩu cũ': 'New password must be different from the old password',
    'Mật khẩu đã được thay đổi thành công!': 'Password changed successfully!',
    'Không thể thay đổi mật khẩu': 'Could not change password',
    'Mật khẩu cũ': 'Old Password',
    'Nhập mật khẩu cũ': 'Enter your old password',
    'Mật khẩu mới': 'New Password',
    'Nhập mật khẩu mới': 'Enter your new password',
    'Xác nhận mật khẩu mới': 'Confirm New Password',
    'Nhập lại mật khẩu mới': 'Confirm your new password',
    'Hiện tại không có lịch chiếu cho phim này': 'There are currently no showtimes for this movie',
    'Hiện tại không có rạp nào có lịch chiếu cho phim này': 'There are currently no cinemas with showtimes for this movie',
    'Đang tải danh sách rạp...': 'Loading list of cinemas...',
    'Chọn rạp chiếu': 'Select cinema',
    'Không có rạp nào có lịch chiếu cho phim này': 'No cinemas have showtimes for this movie',
    'Chọn rạp để xem lịch chiếu': 'Select a cinema to see showtimes',
    'Không có rạp chiếu nào': 'No cinemas available',
    'Lịch Chiếu': 'Showtimes',
    'Không có suất chiếu nào': 'No showtimes available',
    'phút': 'minutes',
    'Đang tải phim yêu thích...': 'Loading favorite movies...',
    'Phim Yêu Thích': 'Favorite Movies',
    ' phim đã lưu': ' movies saved',
    'Bạn chưa có phim yêu thích nào': 'You have no favorite movies yet',
    'Thêm phim vào yêu thích để xem lại sau': 'Add movies to your favorites to watch them later',
    'Khám phá phim': 'Discover movies',
    'Vui lòng nhập email': 'Please enter your email',
    'Vui lòng nhập mã OTP': 'Please enter the OTP code',
    'Mã OTP phải có 6 chữ số': 'OTP code must be 6 digits',
    'Vui lòng nhập mật khẩu mới': 'Please enter a new password',
    'Vui lòng xác nhận mật khẩu': 'Please confirm your password',
    'Đặt lại mật khẩu thất bại': 'Failed to reset password',
    'Quên mật khẩu': 'Forgot Password',
    'Nhập email của bạn để nhận mã OTP': 'Enter your email to receive an OTP code',
    'Nhập mã OTP đã được gửi đến email của bạn': 'Enter the OTP code sent to your email',
    'Đặt mật khẩu mới': 'Set a new password',
    'Nhập mật khẩu mới cho tài khoản của bạn': 'Enter a new password for your account',
    'Đặt lại mật khẩu': 'Reset Password',
    'Thành công!': 'Success!',
    'Mật khẩu của bạn đã được đặt lại thành công': 'Your password has been successfully reset',
    'Bạn có thể sử dụng mật khẩu mới để đăng nhập vào tài khoản của mình.': 'You can use your new password to log in to your account.',
    'Quay lại đăng nhập': 'Back to login',
    'Vui lòng nhập đầy đủ thông tin': 'Please fill in all fields',
    'Đăng nhập thành công': 'Login successful',
    'Đăng nhập thất bại': 'Login failed',
    'Đăng nhập để tiếp tục': 'Login to continue',
    'Đang đăng nhập...': 'Logging in...',
    'Bạn chưa có tài khoản': "Don't have an account?",
    'Đăng ký ngay': 'Register now',
    'Quên mật khẩu?': 'Forgot password?',
    'VNĐ': 'VND',
    'vi-VN': 'en-US',
    'Vui lòng đăng nhập để thêm phim vào yêu thích': 'Please log in to add movies to your favorites',
    'Không thể cập nhật yêu thích. Vui lòng thử lại.': 'Could not update favorites. Please try again.',
    'Không thể mở trailer. Vui lòng kiểm tra URL.': 'Could not open trailer. Please check the URL.',
    'Phim này chưa có trailer': 'This movie does not have a trailer yet',
    'Đang tải thông tin phim...': 'Loading movie information...',
    'Không tìm thấy phim': 'Movie not found',
    'Không có ảnh': 'No image',
    'Xem Trailer': 'Watch Trailer',
    'Mô tả': 'Description',
    'Chưa có mô tả': 'No description yet',
    'Thông tin chi tiết': 'Details',
    'Thể loại:': 'Genre:',
    'Đạo diễn:': 'Director:',
    'Diễn viên:': 'Cast:',
    'Ngôn ngữ:': 'Language:',
    'Phụ đề:': 'Subtitles:',
    'Ngày khởi chiếu:': 'Release Date:',
    'Ngày kết thúc:': 'End Date:',
    'Mua vé': 'Buy Ticket',
    'Chào mừng khách hàng mới': 'Welcome new customer',
    'Giảm 10% cho đơn hàng đầu tiên': '10% off for the first order',
    'Khách hàng VIP': 'VIP Customer',
    'Giảm 20% cho khách hàng VIP': '20% off for VIP customers',
    'Cuối tuần vui vẻ': 'Happy Weekend',
    'Giảm 15% cho suất chiếu cuối tuần': '15% off for weekend showtimes',
    'Giảm giá': 'Discount',
    'Giảm ': 'Discount ',
    'Giảm': 'Discount',
    'Mã:': 'Code:',
    'Đơn tối thiểu:': 'Minimum order:',
    'Giảm tối đa:': 'Maximum discount:',
    'Áp dụng đến:': 'Apply until:',
    'Còn lại:': 'Remaining:',
    'lượt': 'uses',
    'Đã hết hạn': 'Expired',
    'Đã hết lượt': 'Out of uses',
    'Sử dụng mã': 'Use code',
    'Đang áp dụng': 'Active',
    'Có thể dùng': 'Available',
    'Đã hết hạn': 'Expired',
    'Hết hạn': 'Expired',
    'Đơn tối thiểu: ': 'Minimum order: ',
    'Giảm tối đa: ': 'Maximum discount: ',
    'Áp dụng đến: ': 'Apply until: ',
    'Số lượng: ': 'Quantity: ',
    ' lượt': ' uses',
    'Đang tải khuyến mãi...': 'Loading promotions...',
    'Khuyến Mãi': 'Promotions',
    ' khuyến mãi đang áp dụng': ' promotions are being applied',
    'Hiện không có khuyến mãi nào': 'There are no promotions at the moment',
    'Vui lòng quay lại sau để xem các ưu đãi mới': 'Please come back later to see new offers',
    'Không thể tải danh sách ghế': 'Could not load the list of seats',
    'Ghế này đã được đặt': 'This seat is already booked',
    'Vui lòng chọn ít nhất một ghế': 'Please select at least one seat',
    'Đang tải sơ đồ ghế...': 'Loading seat map...',
    'MÀN HÌNH': 'SCREEN',
    'Đã đặt': 'Booked',
    'Ghế bạn chọn': 'Your selection',
    'Ghế thường': 'Normal',
    'Ghế VIP': 'VIP',
    'Ghế couple': 'Couple',
    'Tạm tính': 'Subtotal',
    'Tiếp tục': 'Continue',
    'Trang chủ': 'Home',
    'Yêu thích': 'Favorites',
    'Cá nhân': 'Profile',
    'Tất cả': 'All',
    'Đang chiếu': 'Now Showing',
    'Sắp chiếu': 'Coming Soon',
    'Lỗi kết nối': 'Connection Error',
    'Không thể tải danh sách phim. Vui lòng thử lại.': 'Could not load the list of movies. Please try again.',
    'Khởi chiếu': 'Release Date',
    'Lịch sử đặt vé': 'Booking History',
    'Phim đã xem': 'Watched Movies',
    'Đã xác nhận': 'Confirmed',
    'Đang chờ': 'Pending',
    'Đã hủy': 'Cancelled',
    'Mã đặt vé': 'Booking Code',
    'Tổng tiền': 'Total Amount',
    'Trạng thái': 'Status',
    'Ghế đã đặt': 'Booked Seats',
    'Ngày đặt': 'Booking Date',
    'Chi tiết đặt vé': 'Booking Details',
    'đặt vé': 'bookings',
    'Vui lòng đăng nhập để xem lịch sử đặt vé': 'Please log in to view booking history',
    'Bạn chưa có đặt vé nào': 'You have no bookings yet',
    'Hãy đặt vé để xem phim nhé!': 'Book tickets to watch movies!',
    'Vui lòng đăng nhập để xem phim đã xem': 'Please log in to view watched movies',
    'Bạn chưa xem phim nào': 'You have not watched any movies yet',
    'Hãy đặt vé và xem phim để thêm vào danh sách này!': 'Book tickets and watch movies to add them to this list!',
    'Đang tải lịch sử đặt vé...': 'Loading booking history...',
    'Đang tải phim đã xem...': 'Loading watched movies...',
    'Danh Sách Phim': 'Movie List',
    'Khám phá bộ sưu tập phim đa dạng': 'Discover a diverse collection of movies',
    'Hiện không có phim đang chiếu': 'There are no movies currently showing',
    'Hiện không có phim sắp chiếu': 'There are no upcoming movies',
    'Chào buổi sáng': 'Good morning',
    'Chào buổi chiều': 'Good afternoon',
    'Chào buổi tối': 'Good evening',
    'Chào mừng bạn!': 'Welcome!',
    'Khám phá những bộ phim hay': 'Discover great movies',
    'KM': 'Promo',
    'Tìm kiếm phim...': 'Search for movies...',
    'Không tìm thấy phim nào với từ khóa "{searchText}"': 'No movies found with the keyword "{searchText}"',
    'Thử tìm kiếm với từ khóa khác': 'Try searching with a different keyword',
    'Không có phim nào': 'No movies available',
    'Đang tải danh sách phim...': 'Loading movie list...',
    'N/A': 'N/A',
    'Login failed': 'Login failed',
    'Registration failed': 'Registration failed',
    'Failed to get user info': 'Failed to get user info',
    'Failed to change password': 'Failed to change password',
    'OTP sent successfully': 'OTP sent successfully',
    'Failed to send OTP': 'Failed to send OTP',
    'OTP verified successfully': 'OTP verified successfully',
    'OTP verification failed': 'OTP verification failed',
    'Login with OTP failed': 'Login with OTP failed',
    'Movie Ticket Booking': 'Movie Ticket Booking',
    'Demo accounts:': 'Demo accounts:',
    'Admin:': 'Admin:',
    'Staff:': 'Staff:',
    'Customer:': 'Customer:',
  },
  vi: {
    'Bạn chưa đăng nhập': 'Bạn chưa đăng nhập',
    'Hãy đăng nhập để sử dụng các chức năng cá nhân hóa!': 'Hãy đăng nhập để sử dụng các chức năng cá nhân hóa!',
    'Đăng nhập': 'Đăng nhập',
    'hoặc': 'hoặc',
    'Tạo tài khoản': 'Tạo tài khoản',
    'Đăng xuất': 'Đăng xuất',
    'Bạn có chắc chắn muốn đăng xuất?': 'Bạn có chắc chắn muốn đăng xuất?',
    'Hủy': 'Hủy',
    'Thông tin cá nhân': 'Thông tin cá nhân',
    'Tên đăng nhập:': 'Tên đăng nhập:',
    'Email:': 'Email:',
    'Số điện thoại:': 'Số điện thoại:',
    'Ngày sinh:': 'Ngày sinh:',
    'Giới tính:': 'Giới tính:',
    'Nam': 'Nam',
    'Nữ': 'Nữ',
    'Chức năng': 'Chức năng',
    'Phim yêu thích': 'Phim yêu thích',
    'Cinema': 'Rạp chiếu phim',
    'Khuyến mãi': 'Khuyến mãi',
    'Cài đặt': 'Cài đặt',
    'Quản lý hệ thống': 'Quản lý hệ thống',
    'Quản lý đặt vé': 'Quản lý đặt vé',
    'Đổi mật khẩu': 'Đổi mật khẩu',
    'Chế độ tối': 'Chế độ tối',
    'Ngôn ngữ (English/Tiếng Việt)': 'Ngôn ngữ (English/Tiếng Việt)',
    'Đóng': 'Đóng',
    "Quản trị viên": "Quản trị viên",
    "Nhân viên": "Nhân viên",
    "Khách hàng": "Khách hàng",
    "Email không được để trống": "Email không được để trống",
    "Email không hợp lệ": "Email không hợp lệ",
    "OTP không được để trống": "OTP không được để trống",
    "OTP phải có 6 chữ số": "OTP phải có 6 chữ số",
    "Họ tên không được để trống": "Họ tên không được để trống",
    "Số điện thoại không được để trống": "Số điện thoại không được để trống",
    "Số điện thoại không hợp lệ (10-11 chữ số)": "Số điện thoại không hợp lệ (10-11 chữ số)",
    "Tên đăng nhập không được để trống": "Tên đăng nhập không được để trống",
    "Tên đăng nhập phải có ít nhất 3 ký tự": "Tên đăng nhập phải có ít nhất 3 ký tự",
    "Mật khẩu không được để trống": "Mật khẩu không được để trống",
    "Mật khẩu phải có ít nhất 6 ký tự": "Mật khẩu phải có ít nhất 6 ký tự",
    "Xác nhận mật khẩu không được để trống": "Xác nhận mật khẩu không được để trống",
    "Mật khẩu xác nhận không khớp": "Mật khẩu xác nhận không khớp",
    "Ngày sinh không được để trống": "Ngày sinh không được để trống",
    "Định dạng ngày sinh phải là YYYY-MM-DD": "Định dạng ngày sinh phải là YYYY-MM-DD",
    "Năm sinh phải từ 1900 đến 2010": "Năm sinh phải từ 1900 đến 2010",
    "Tháng phải từ 01 đến 12": "Tháng phải từ 01 đến 12",
    "Ngày phải từ 01 đến {daysInMonth} cho tháng {month}": "Ngày phải từ 01 đến {daysInMonth} cho tháng {month}",
    "Thành công": "Thành công",
    "OTP đã được gửi đến email của bạn": "OTP đã được gửi đến email của bạn",
    "Lỗi": "Lỗi",
    "Không thể gửi OTP": "Không thể gửi OTP",
    "OTP hợp lệ! Vui lòng nhập thông tin tài khoản": "OTP hợp lệ! Vui lòng nhập thông tin tài khoản",
    "OTP không hợp lệ": "OTP không hợp lệ",
    "OTP mới đã được gửi": "OTP mới đã được gửi",
    "Nhập email của bạn": "Nhập email của bạn",
    "Nhập 6 chữ số OTP": "Nhập 6 chữ số OTP",
    "Nhập họ và tên": "Nhập họ và tên",
    "Nhập số điện thoại": "Nhập số điện thoại",
    "Nhập tên đăng nhập": "Nhập tên đăng nhập",
    "Nhập mật khẩu": "Nhập mật khẩu",
    "Nhập lại mật khẩu": "Nhập lại mật khẩu",
    "Đăng ký tài khoản thành công!": "Đăng ký tài khoản thành công!",
    "Đăng ký thất bại": "Đăng ký thất bại",
    "OTP mới đã được gửi": "OTP mới đã được gửi",
    "Quay lại": "Quay lại",
    "Đăng ký": "Đăng ký",
    "Email": "Email",
    "Nhập email của bạn": "Nhập email của bạn",
    "Gửi OTP": "Gửi OTP",
    "Mã OTP": "Mã OTP",
    "Nhập 6 chữ số OTP": "Nhập 6 chữ số OTP",
    "OTP hết hạn sau:": "OTP hết hạn sau:",
    "Xác thực OTP": "Xác thực OTP",
    "Gửi lại OTP": "Gửi lại OTP",
    "Họ và tên": "Họ và tên",
    "Nhập họ và tên": "Nhập họ và tên",
    "Số điện thoại": "Số điện thoại",
    "Nhập số điện thoại": "Nhập số điện thoại",
    "Tên đăng nhập": "Tên đăng nhập",
    "Nhập tên đăng nhập": "Nhập tên đăng nhập",
    "Mật khẩu": "Mật khẩu",
    "Nhập mật khẩu": "Nhập mật khẩu",
    "Xác nhận mật khẩu": "Xác nhận mật khẩu",
    "Nhập lại mật khẩu": "Nhập lại mật khẩu",
    "Ngày sinh": "Ngày sinh",
    "YYYY-MM-DD (ví dụ: 1990-01-15)": "YYYY-MM-DD (ví dụ: 1990-01-15)",
    "Định dạng: YYYY-MM-DD (ví dụ: 1990-01-15)": "Định dạng: YYYY-MM-DD (ví dụ: 1990-01-15)",
    "Đăng ký tài khoản mới": "Đăng ký tài khoản mới",
    "Đã có tài khoản?": "Đã có tài khoản?",
    "Đang xử lý...": "Đang xử lý...",
    'Không thể tải thông tin phim': 'Không thể tải thông tin phim',
    'Không thể tải danh sách rạp': 'Không thể tải danh sách rạp',
    'Không thể tải suất chiếu': 'Không thể tải suất chiếu',
    'Chọn rạp': 'Chọn rạp',
    'Chọn ngày': 'Chọn ngày',
    'Suất chiếu': 'Suất chiếu',
    'Không có suất chiếu cho ngày này.': 'Không có suất chiếu cho ngày này.',
    'Đang tải...': 'Đang tải...',
    'Lỗi tải dữ liệu': 'Lỗi tải dữ liệu',
    'Thử lại': 'Thử lại',
    'Chọn suất chiếu': 'Chọn suất chiếu',
    'Ngày': 'Ngày',
    'Rạp': 'Rạp',
    'Vui lòng nhập mã giảm giá': 'Vui lòng nhập mã giảm giá',
    'Mã giảm giá không hợp lệ hoặc đã hết hạn': 'Mã giảm giá không hợp lệ hoặc đã hết hạn',
    'Đơn hàng tối thiểu {minAmount} VNĐ để áp dụng mã này': 'Đơn hàng tối thiểu {minAmount} VNĐ để áp dụng mã này',
    'Đã áp dụng mã giảm giá: {name}': 'Đã áp dụng mã giảm giá: {name}',
    'Không thể kiểm tra mã giảm giá. Vui lòng thử lại.': 'Không thể kiểm tra mã giảm giá. Vui lòng thử lại.',
    'Vui lòng chọn ghế': 'Vui lòng chọn ghế',
    'Không tìm thấy thông tin suất chiếu': 'Không tìm thấy thông tin suất chiếu',
    'Thông báo': 'Thông báo',
    'Vui lòng đăng nhập để đặt vé': 'Vui lòng đăng nhập để đặt vé',
    'Đặt vé thành công!': 'Đặt vé thành công!',
    'Đặt vé thất bại': 'Đặt vé thất bại',
    'Đặt vé': 'Đặt vé',
    'Phim': 'Phim',
    'Rạp chiếu': 'Rạp chiếu',
    'Phòng chiếu': 'Phòng chiếu',
    'Ghế đã chọn': 'Ghế đã chọn',
    'ghế đã chọn': 'ghế đã chọn',
    'Chưa chọn ghế': 'Chưa chọn ghế',
    'Mã giảm giá (tùy chọn)': 'Mã giảm giá (tùy chọn)',
    'Nhập mã giảm giá': 'Nhập mã giảm giá',
    'Áp dụng': 'Áp dụng',
    'Xóa mã': 'Xóa mã',
    'Tóm tắt đơn hàng': 'Tóm tắt đơn hàng',
    'Số ghế đã chọn:': 'Số ghế đã chọn:',
    'Số lượng ghế:': 'Số lượng ghế:',
    'ghế': 'ghế',
    'Giá mỗi vé:': 'Giá mỗi vé:',
    'Giảm giá:': 'Giảm giá:',
    'Tổng cộng:': 'Tổng cộng:',
    'Mật khẩu cũ không được để trống': 'Mật khẩu cũ không được để trống',
    'Mật khẩu mới không được để trống': 'Mật khẩu mới không được để trống',
    'Mật khẩu mới phải có ít nhất 6 ký tự': 'Mật khẩu mới phải có ít nhất 6 ký tự',
    'Mật khẩu mới phải khác mật khẩu cũ': 'Mật khẩu mới phải khác mật khẩu cũ',
    'Mật khẩu đã được thay đổi thành công!': 'Mật khẩu đã được thay đổi thành công!',
    'Không thể thay đổi mật khẩu': 'Không thể thay đổi mật khẩu',
    'Mật khẩu cũ': 'Mật khẩu cũ',
    'Nhập mật khẩu cũ': 'Nhập mật khẩu cũ',
    'Mật khẩu mới': 'Mật khẩu mới',
    'Nhập mật khẩu mới': 'Nhập mật khẩu mới',
    'Xác nhận mật khẩu mới': 'Xác nhận mật khẩu mới',
    'Nhập lại mật khẩu mới': 'Nhập lại mật khẩu mới',
    'Hiện tại không có lịch chiếu cho phim này': 'Hiện tại không có lịch chiếu cho phim này',
    'Hiện tại không có rạp nào có lịch chiếu cho phim này': 'Hiện tại không có rạp nào có lịch chiếu cho phim này',
    'Đang tải danh sách rạp...': 'Đang tải danh sách rạp...',
    'Chọn rạp chiếu': 'Chọn rạp chiếu',
    'Không có rạp nào có lịch chiếu cho phim này': 'Không có rạp nào có lịch chiếu cho phim này',
    'Chọn rạp để xem lịch chiếu': 'Chọn rạp để xem lịch chiếu',
    'Không có rạp chiếu nào': 'Không có rạp chiếu nào',
    'Lịch Chiếu': 'Lịch Chiếu',
    'Không có suất chiếu nào': 'Không có suất chiếu nào',
    'phút': 'phút',
    'Đang tải phim yêu thích...': 'Đang tải phim yêu thích...',
    'Phim Yêu Thích': 'Phim Yêu Thích',
    ' phim đã lưu': ' phim đã lưu',
    'Bạn chưa có phim yêu thích nào': 'Bạn chưa có phim yêu thích nào',
    'Thêm phim vào yêu thích để xem lại sau': 'Thêm phim vào yêu thích để xem lại sau',
    'Khám phá phim': 'Khám phá phim',
    'Vui lòng nhập email': 'Vui lòng nhập email',
    'Vui lòng nhập mã OTP': 'Vui lòng nhập mã OTP',
    'Mã OTP phải có 6 chữ số': 'Mã OTP phải có 6 chữ số',
    'Vui lòng nhập mật khẩu mới': 'Vui lòng nhập mật khẩu mới',
    'Vui lòng xác nhận mật khẩu': 'Vui lòng xác nhận mật khẩu',
    'Đặt lại mật khẩu thất bại': 'Đặt lại mật khẩu thất bại',
    'Quên mật khẩu': 'Quên mật khẩu',
    'Nhập email của bạn để nhận mã OTP': 'Nhập email của bạn để nhận mã OTP',
    'Nhập mã OTP đã được gửi đến email của bạn': 'Nhập mã OTP đã được gửi đến email của bạn',
    'Đặt mật khẩu mới': 'Đặt mật khẩu mới',
    'Nhập mật khẩu mới cho tài khoản của bạn': 'Nhập mật khẩu mới cho tài khoản của bạn',
    'Đặt lại mật khẩu': 'Đặt lại mật khẩu',
    'Thành công!': 'Thành công!',
    'Mật khẩu của bạn đã được đặt lại thành công': 'Mật khẩu của bạn đã được đặt lại thành công',
    'Bạn có thể sử dụng mật khẩu mới để đăng nhập vào tài khoản của mình.': 'Bạn có thể sử dụng mật khẩu mới để đăng nhập vào tài khoản của mình.',
    'Quay lại đăng nhập': 'Quay lại đăng nhập',
    'Vui lòng nhập đầy đủ thông tin': 'Vui lòng nhập đầy đủ thông tin',
    'Đăng nhập thành công': 'Đăng nhập thành công',
    'Đăng nhập thất bại': 'Đăng nhập thất bại',
    'Đăng nhập để tiếp tục': 'Đăng nhập để tiếp tục',
    'Đang đăng nhập...': 'Đang đăng nhập...',
    'Bạn chưa có tài khoản': 'Bạn chưa có tài khoản',
    'Đăng ký ngay': 'Đăng ký ngay',
    'Quên mật khẩu?': 'Quên mật khẩu?',
    'VNĐ': 'VNĐ',
    'vi-VN': 'vi-VN',
    'Vui lòng đăng nhập để thêm phim vào yêu thích': 'Vui lòng đăng nhập để thêm phim vào yêu thích',
    'Không thể cập nhật yêu thích. Vui lòng thử lại.': 'Không thể cập nhật yêu thích. Vui lòng thử lại.',
    'Không thể mở trailer. Vui lòng kiểm tra URL.': 'Không thể mở trailer. Vui lòng kiểm tra URL.',
    'Phim này chưa có trailer': 'Phim này chưa có trailer',
    'Đang tải thông tin phim...': 'Đang tải thông tin phim...',
    'Không tìm thấy phim': 'Không tìm thấy phim',
    'Không có ảnh': 'Không có ảnh',
    'Xem Trailer': 'Xem Trailer',
    'Mô tả': 'Mô tả',
    'Chưa có mô tả': 'Chưa có mô tả',
    'Thông tin chi tiết': 'Thông tin chi tiết',
    'Thể loại:': 'Thể loại:',
    'Đạo diễn:': 'Đạo diễn:',
    'Diễn viên:': 'Diễn viên:',
    'Ngôn ngữ:': 'Ngôn ngữ:',
    'Phụ đề:': 'Phụ đề:',
    'Ngày khởi chiếu:': 'Ngày khởi chiếu:',
    'Ngày kết thúc:': 'Ngày kết thúc:',
    'Mua vé': 'Mua vé',
    'Chào mừng khách hàng mới': 'Chào mừng khách hàng mới',
    'Giảm 10% cho đơn hàng đầu tiên': 'Giảm 10% cho đơn hàng đầu tiên',
    'Khách hàng VIP': 'Khách hàng VIP',
    'Giảm 20% cho khách hàng VIP': 'Giảm 20% cho khách hàng VIP',
    'Cuối tuần vui vẻ': 'Cuối tuần vui vẻ',
    'Giảm 15% cho suất chiếu cuối tuần': 'Giảm 15% cho suất chiếu cuối tuần',
    'Giảm giá': 'Giảm giá',
    'Giảm ': 'Giảm ',
    'Giảm': 'Giảm',
    'Mã:': 'Mã:',
    'Đơn tối thiểu:': 'Đơn tối thiểu:',
    'Giảm tối đa:': 'Giảm tối đa:',
    'Áp dụng đến:': 'Áp dụng đến:',
    'Còn lại:': 'Còn lại:',
    'lượt': 'lượt',
    'Đã hết hạn': 'Đã hết hạn',
    'Đã hết lượt': 'Đã hết lượt',
    'Sử dụng mã': 'Sử dụng mã',
    'Đang áp dụng': 'Đang áp dụng',
    'Có thể dùng': 'Có thể dùng',
    'Hết hạn': 'Hết hạn',
    'Đơn tối thiểu: ': 'Đơn tối thiểu: ',
    'Giảm tối đa: ': 'Giảm tối đa: ',
    'Áp dụng đến: ': 'Áp dụng đến: ',
    'Số lượng: ': 'Số lượng: ',
    ' lượt': ' lượt',
    'Đang tải khuyến mãi...': 'Đang tải khuyến mãi...',
    'Khuyến Mãi': 'Khuyến Mãi',
    ' khuyến mãi đang áp dụng': ' khuyến mãi đang áp dụng',
    'Hiện không có khuyến mãi nào': 'Hiện không có khuyến mãi nào',
    'Vui lòng quay lại sau để xem các ưu đãi mới': 'Vui lòng quay lại sau để xem các ưu đãi mới',
    'Không thể tải danh sách ghế': 'Không thể tải danh sách ghế',
    'Ghế này đã được đặt': 'Ghế này đã được đặt',
    'Vui lòng chọn ít nhất một ghế': 'Vui lòng chọn ít nhất một ghế',
    'Đang tải sơ đồ ghế...': 'Đang tải sơ đồ ghế...',
    'MÀN HÌNH': 'MÀN HÌNH',
    'Đã đặt': 'Đã đặt',
    'Ghế bạn chọn': 'Ghế bạn chọn',
    'Ghế thường': 'Ghế thường',
    'Ghế VIP': 'Ghế VIP',
    'Ghế couple': 'Ghế couple',
    'Tạm tính': 'Tạm tính',
    'Tiếp tục': 'Tiếp tục',
    'Trang chủ': 'Trang chủ',
    'Yêu thích': 'Yêu thích',
    'Cá nhân': 'Cá nhân',
    'Tất cả': 'Tất cả',
    'Đang chiếu': 'Đang chiếu',
    'Sắp chiếu': 'Sắp chiếu',
    'Lỗi kết nối': 'Lỗi kết nối',
    'Không thể tải danh sách phim. Vui lòng thử lại.': 'Không thể tải danh sách phim. Vui lòng thử lại.',
    'Khởi chiếu': 'Khởi chiếu',
    'Lịch sử đặt vé': 'Lịch sử đặt vé',
    'Phim đã xem': 'Phim đã xem',
    'Đã xác nhận': 'Đã xác nhận',
    'Đang chờ': 'Đang chờ',
    'Đã hủy': 'Đã hủy',
    'Mã đặt vé': 'Mã đặt vé',
    'Tổng tiền': 'Tổng tiền',
    'Trạng thái': 'Trạng thái',
    'Ghế đã đặt': 'Ghế đã đặt',
    'Ngày đặt': 'Ngày đặt',
    'Chi tiết đặt vé': 'Chi tiết đặt vé',
    'đặt vé': 'đặt vé',
    'Vui lòng đăng nhập để xem lịch sử đặt vé': 'Vui lòng đăng nhập để xem lịch sử đặt vé',
    'Bạn chưa có đặt vé nào': 'Bạn chưa có đặt vé nào',
    'Hãy đặt vé để xem phim nhé!': 'Hãy đặt vé để xem phim nhé!',
    'Vui lòng đăng nhập để xem phim đã xem': 'Vui lòng đăng nhập để xem phim đã xem',
    'Bạn chưa xem phim nào': 'Bạn chưa xem phim nào',
    'Hãy đặt vé và xem phim để thêm vào danh sách này!': 'Hãy đặt vé và xem phim để thêm vào danh sách này!',
    'Đang tải lịch sử đặt vé...': 'Đang tải lịch sử đặt vé...',
    'Đang tải phim đã xem...': 'Đang tải phim đã xem...',
    'Danh Sách Phim': 'Danh Sách Phim',
    'Khám phá bộ sưu tập phim đa dạng': 'Khám phá bộ sưu tập phim đa dạng',
    'Hiện không có phim đang chiếu': 'Hiện không có phim đang chiếu',
    'Hiện không có phim sắp chiếu': 'Hiện không có phim sắp chiếu',
    'Chào buổi sáng': 'Chào buổi sáng',
    'Chào buổi chiều': 'Chào buổi chiều',
    'Chào buổi tối': 'Chào buổi tối',
    'Chào mừng bạn!': 'Chào mừng bạn!',
    'Khám phá những bộ phim hay': 'Khám phá những bộ phim hay',
    'KM': 'KM',
    'Tìm kiếm phim...': 'Tìm kiếm phim...',
    'Không tìm thấy phim nào với từ khóa "{searchText}"': 'Không tìm thấy phim nào với từ khóa "{searchText}"',
    'Thử tìm kiếm với từ khóa khác': 'Thử tìm kiếm với từ khóa khác',
    'Không có phim nào': 'Không có phim nào',
    'Đang tải danh sách phim...': 'Đang tải danh sách phim...',
    'N/A': 'N/A',
    'Login failed': 'Đăng nhập thất bại',
    'Registration failed': 'Đăng ký thất bại',
    'Failed to get user info': 'Không thể lấy thông tin người dùng',
    'Failed to change password': 'Không thể thay đổi mật khẩu',
    'OTP sent successfully': 'Gửi OTP thành công',
    'Failed to send OTP': 'Gửi OTP thất bại',
    'OTP verified successfully': 'Xác thực OTP thành công',
    'OTP verification failed': 'Xác thực OTP thất bại',
    'Login with OTP failed': 'Đăng nhập bằng OTP thất bại',
    'Movie Ticket Booking': 'Đặt Vé Xem Phim',
    'Demo accounts:': 'Tài khoản demo:',
    'Admin:': 'Admin:',
    'Staff:': 'Nhân viên:',
    'Customer:': 'Khách hàng:',
    'Xác nhận thanh toán': 'Xác nhận thanh toán',
    'Bạn có chắc chắn muốn thanh toán {amount} VNĐ bằng phương thức {method}?': 'Bạn có chắc chắn muốn thanh toán {amount} VNĐ bằng phương thức {method}?',
    'Xác nhận': 'Xác nhận',
    'Không tìm thấy vé với mã: {code}': 'Không tìm thấy vé với mã: {code}',
    'Phương thức thanh toán': 'Phương thức thanh toán',
    'Tiền mặt': 'Tiền mặt',
    'Chuyển khoản': 'Chuyển khoản',
    'Thẻ tín dụng': 'Thẻ tín dụng',
    'Chưa xác định': 'Chưa xác định',
    'Khuyến mãi có thể áp dụng': 'Khuyến mãi có thể áp dụng',
    'Không có khuyến mãi nào khả dụng': 'Không có khuyến mãi nào khả dụng',
    'Bỏ chọn khuyến mãi': 'Bỏ chọn khuyến mãi',
    'Tiết kiệm:': 'Tiết kiệm:',
    'Áp dụng cho đơn từ': 'Áp dụng cho đơn từ',
    'Chi tiết vé': 'Chi tiết vé',
    'Mã QR vé': 'Mã QR vé',
    'Thông tin đặt vé': 'Thông tin đặt vé',
    'Thông tin phim': 'Thông tin phim',
    'Thông tin rạp': 'Thông tin rạp',
    'Thông tin khách hàng': 'Thông tin khách hàng',
    'Thông tin thanh toán': 'Thông tin thanh toán',
    'Xuất vé PDF': 'Xuất vé PDF',
    'Quét mã QR vé': 'Quét mã QR vé',
    'Đưa mã QR vào khung để quét': 'Đưa mã QR vào khung để quét',
    'Quét lại': 'Quét lại',
    'Cần quyền truy cập camera để quét mã QR': 'Cần quyền truy cập camera để quét mã QR',
    'Cấp quyền': 'Cấp quyền',
  },
};

export const useTranslation = () => {
  const language = useSelector((state: RootState) => state.language?.language || 'vi');

  return (key: keyof typeof translations.en, params?: { [key: string]: string | number }) => {
    const lang = language as 'vi' | 'en';
    let translation = translations[lang]?.[key] || translations.en[key] || key;
    if (params) {
      Object.keys(params).forEach(paramKey => {
        translation = translation.replace(`{${paramKey}}`, String(params[paramKey]));
      });
    }
    return translation;
  };
};
